# Generated by Django 6.0.4 on 2026-04-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL unique de l'activité", unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.CharField(help_text='Description courte', max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Nom de l'icône Lucide (ex: MessageCircle)", max_length=50)),
                ('color', models.CharField(help_text='Code couleur hex (ex: #002D62)', max_length=20)),
                ('tag', models.CharField(max_length=50)),
                ('next_event', models.CharField(blank=True, help_text='Texte libre indiquant la date du prochain événement', max_length=150, null=True)),
                ('location', models.CharField(max_length=200)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('achievements', models.JSONField(default=list, help_text='Liste des réalisations (format JSON)')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(help_text="Année de l'album")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Album Galerie',
                'verbose_name_plural': 'Albums Galerie',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='Catégorie affichée (ex: Mémoire)', max_length=100)),
                ('tag', models.CharField(help_text='Sert uniquement aux couleurs, ex: commemoration, formation', max_length=50)),
                ('date', models.DateField()),
                ('excerpt', models.TextField(help_text='Extrait visible sur la carte')),
                ('content', models.TextField(help_text="Contenu complet de l'article")),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
            ],
            options={
                'verbose_name': 'Article / Actualité',
                'verbose_name_plural': 'Articles / Actualités',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom et nom')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant ($)')),
                ('is_monthly', models.BooleanField(default=False, verbose_name='Don Mensuel ?')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Contacté / En cours'), ('completed', 'Finalisé')], default='pending', max_length=50, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promesse de Don',
                'verbose_name_plural': 'Promesses de Don',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_slides/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PastEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('count', models.PositiveIntegerField(help_text='Nombre de participants')),
                ('highlight', models.TextField(help_text="Fait marquant de l'édition")),
            ],
            options={
                'verbose_name': 'Édition passée',
                'verbose_name_plural': 'Éditions passées',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=200)),
                ('icon_name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='Horaire direct (ex: 10h00 - 12h00)', max_length=100)),
                ('event', models.CharField(help_text='Titre de la session', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Point du Programme',
                'verbose_name_plural': 'Programme des commémorations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ARMMK', max_length=100)),
                ('about_text', models.TextField(blank=True, help_text="Texte d'à propos global")),
                ('contact_email', models.EmailField(default='contact@armmk.org', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuration du Site',
                'verbose_name_plural': 'Configuration du Site',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du témoin', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('teaser', models.CharField(help_text="Citation courte d'accroche", max_length=255)),
                ('excerpt', models.TextField(help_text='Extrait pour la carte')),
                ('full_text', models.TextField(help_text='Témoignage complet')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
            },
        ),
        migrations.CreateModel(
            name='SupportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Nom lucide-react (ex: HandHeart)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Forme de Soutien',
                'verbose_name_plural': 'Formes de Soutien',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('initials', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('dialogue', 'Dialogue'), ('formation', 'Formation'), ('soutien', 'Soutien'), ('commemoration', 'Commémoration'), ('gouvernance', 'Gouvernance')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, help_text="Texte libre pour l'horaire", max_length=100, null=True)),
                ('location', models.CharField(max_length=200)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.activity')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to='albums/')),
                ('alt', models.CharField(blank=True, help_text="Description de l'image (SEO)", max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.album')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['order'],
            },
        ),
    ]
