# Generated by Django 6.0.4 on 2026-04-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('rapports', 'Rapports annuels'), ('communiques', 'Communiqués'), ('archives', 'Archives historiques'), ('ressources', 'Ressources pédagogiques')], max_length=20)),
                ('date', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('pages', models.PositiveIntegerField()),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('XLSX', 'XLSX')], max_length=10)),
                ('language', models.CharField(choices=[('FR', 'Français'), ('EN', 'English'), ('SW', 'Swahili')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('downloadUrl', models.URLField(blank=True, help_text='Lien externe (si pas de fichier)')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document / Rapport',
                'verbose_name_plural': 'Documents / Rapports',
                'ordering': ['-featured', 'order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(help_text='Ex: ONG Internationale', max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('href', models.URLField(blank=True, default='#')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom et Prénom')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='Contact')),
                ('relation', models.CharField(max_length=100, verbose_name='Lien avec le massacre')),
                ('message', models.TextField(verbose_name='Témoignage')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Validé ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soumission de Témoignage',
                'verbose_name_plural': 'Soumissions de Témoignages',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='Ex: 30 DÉC. 1998', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Evènement Chronologique',
                'verbose_name_plural': 'Frise Chronologique (Massacre)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Valeur / Croyance',
                'verbose_name_plural': 'Valeurs / Croyances',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='story',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
