# Generated by Django 6.0.3 on 2026-04-20 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_partner_testimonysubmission_timelineevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommemorationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_text', models.CharField(help_text='Ex: 30 Décembre 2025 – 2 Janvier 2026', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('countdown_day', models.CharField(help_text='Ex: 30', max_length=10)),
                ('countdown_month_year', models.CharField(help_text='Ex: Décembre 2026', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='commemoration/')),
            ],
            options={
                'verbose_name': 'Section Commémoration (Accueil)',
                'verbose_name_plural': 'Section Commémoration (Accueil)',
            },
        ),
        migrations.CreateModel(
            name='HomeCTAAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(help_text='Nom Lucide icon', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('href', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Action CTA (Accueil)',
                'verbose_name_plural': 'Actions CTA (Accueil)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('sub', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_overflow', models.BooleanField(default=False, help_text="Affiché dans le menu 'Plus'")),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navlink')),
            ],
            options={
                'verbose_name': 'Lien de Navigation',
                'verbose_name_plural': 'Liens de Navigation',
                'ordering': ['order'],
            },
        ),
    ]
