# Generated by Django 6.0.3 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commemorationsection_homectaaction_statistic_navlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_history_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_history_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_history_title',
            field=models.CharField(blank=True, default='Née de la douleur, portée par la dignité', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='vision_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_text',
            field=models.TextField(blank=True, help_text="Texte d'à propos global (footer/home)"),
        ),
    ]
