# Generated by Django 6.0.3 on 2026-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_about_history_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='massacre_intro_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='massacre_intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='massacre/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='massacre_intro_title',
            field=models.CharField(blank=True, default="Un crime contre l'humanité en plein cœur du Congo", max_length=255),
        ),
    ]
