# Generated by Django 6.0.3 on 2026-04-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_massacre_intro_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
