# Generated by Django 6.0.4 on 2026-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activity_description_en_activity_description_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Lieu de mémoire', max_length=100)),
                ('badge_en', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_es', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(default='Le site mémorial de Makobola', max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('location', models.CharField(default='Makobola, Territoire de Fizi, Sud-Kivu, RDC', max_length=255)),
                ('location_en', models.CharField(blank=True, max_length=255, null=True)),
                ('location_es', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='memorial/')),
            ],
            options={
                'verbose_name': 'Lieu de Mémoire',
                'verbose_name_plural': 'Lieu de Mémoire',
            },
        ),
    ]
