# Generated by Django 6.0.4 on 2026-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_memorialsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(help_text='Ex: $10', max_length=50)),
                ('impact', models.CharField(max_length=255)),
                ('impact_en', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_es', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Impact de don',
                'verbose_name_plural': 'Impacts de don',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='value',
            name='icon_name',
            field=models.CharField(default='Heart', help_text="Nom de l'icône (ex: Heart, Scale, Handshake, Shield)", max_length=50),
        ),
    ]
