# Generated by Django 6.0.4 on 2026-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_donationimpact_value_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo (ex: https://www.youtube.com/watch?v=...)', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo (ex: https://www.youtube.com/watch?v=...)', null=True),
        ),
    ]
