# Generated by Django 6.0.4 on 2026-04-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activity_video_url_article_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField(help_text='Lien YouTube ou Vimeo')),
                ('order', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.album')),
            ],
            options={
                'verbose_name': 'Vidéo Galerie',
                'verbose_name_plural': 'Vidéos Galerie',
                'ordering': ['order'],
            },
        ),
    ]
