# Generated by Django 6.0.4 on 2026-05-02 13:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Article / Actualité', 'verbose_name_plural': 'Articles / Actualités'},
        ),
        migrations.AlterModelOptions(
            name='commemorationsection',
            options={'verbose_name': 'Section Commémoration (Accueil)', 'verbose_name_plural': 'Section Commémoration (Accueil)'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'à‰vènement', 'verbose_name_plural': 'à‰vènements'},
        ),
        migrations.AlterModelOptions(
            name='memorialsite',
            options={'verbose_name': 'Lieu de Mémoire', 'verbose_name_plural': 'Lieu de Mémoire'},
        ),
        migrations.AlterModelOptions(
            name='pastedition',
            options={'ordering': ['-year'], 'verbose_name': 'à‰dition passée', 'verbose_name_plural': 'à‰ditions passées'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['order'], 'verbose_name': 'Méthode de paiement', 'verbose_name_plural': 'Méthodes de paiement'},
        ),
        migrations.AlterModelOptions(
            name='programmeitem',
            options={'ordering': ['order'], 'verbose_name': 'Point du Programme', 'verbose_name_plural': 'Programme des commémorations'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': "Membre de l'équipe", 'verbose_name_plural': "Membres de l'équipe"},
        ),
        migrations.AlterModelOptions(
            name='testimonysubmission',
            options={'verbose_name': 'Soumission de Témoignage', 'verbose_name_plural': 'Soumissions de Témoignages'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order'], 'verbose_name': 'à‰vénement Chronologique', 'verbose_name_plural': 'Frise Chronologique (Massacre)'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order'], 'verbose_name': 'Vidéo Galerie', 'verbose_name_plural': 'Vidéos Galerie'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='activity',
            name='achievements',
            field=models.JSONField(default=list, help_text='Liste des réalisations (format JSON)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.CharField(help_text="Nom de l'icà´ne Lucide (ex: MessageCircle)", max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='next_event',
            field=models.CharField(blank=True, help_text='Texte libre indiquant la date du prochain à‰vénement', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(help_text="URL unique de l'activité", unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(help_text="Année de l'album"),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(help_text='Catégorie affichée (ex: Mémoire)', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text="Contenu complet de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commemorationsection',
            name='countdown_month_year',
            field=models.CharField(help_text='Ex: Décembre 2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='commemorationsection',
            name='date_text',
            field=models.CharField(help_text='Ex: 30 Décembre 2025 â€“ 2 Janvier 2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='commemorationsection',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='commemorationsection',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commemorationsection',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('rapports', 'Rapports annuels'), ('communiques', 'Communiqués'), ('archives', 'Archives historiques'), ('ressources', 'Ressources pédagogiques')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('FR', 'Franà§ais'), ('EN', 'English'), ('SW', 'Swahili')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donationintent',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom et nom'),
        ),
        migrations.AlterField(
            model_name='donationintent',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Contacté / En cours'), ('completed', 'Finalisé')], default='pending', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('dialogue', 'Dialogue'), ('formation', 'Formation'), ('soutien', 'Soutien'), ('commemoration', 'Commémoration'), ('gouvernance', 'Gouvernance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='homectaaction',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homectaaction',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorialsite',
            name='badge',
            field=models.CharField(default='Lieu de mémoire', max_length=100),
        ),
        migrations.AlterField(
            model_name='memorialsite',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorialsite',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorialsite',
            name='title',
            field=models.CharField(default='Le site mémorial de Makobola', max_length=255),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='is_overflow',
            field=models.BooleanField(default=False, help_text="Affiché dans le menu 'Plus'"),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastedition',
            name='highlight',
            field=models.TextField(help_text="Fait marquant de l'édition"),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_history_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_history_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_history_content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_history_title',
            field=models.CharField(blank=True, default='Née de la douleur, portée par la dignité', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_text',
            field=models.TextField(blank=True, help_text="Texte d'à\xa0 propos global (footer/home)"),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='massacre_intro_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='massacre_intro_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='massacre_intro_content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='massacre_intro_title',
            field=models.CharField(blank=True, default="Un crime contre l'humanité en plein cÅ“ur du Congo", max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mission_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mission_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mission_text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='vision_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='vision_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='vision_text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='full_text',
            field=models.TextField(help_text='Témoignage complet'),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(help_text='Nom du témoin', max_length=150),
        ),
        migrations.AlterField(
            model_name='supportform',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportform',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonysubmission',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Validé ?'),
        ),
        migrations.AlterField(
            model_name='testimonysubmission',
            name='message',
            field=models.TextField(verbose_name='Témoignage'),
        ),
        migrations.AlterField(
            model_name='testimonysubmission',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom et Prénom'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.CharField(help_text='Ex: 30 DEC. 1998', max_length=50),
        ),
        migrations.AlterField(
            model_name='value',
            name='icon_name',
            field=models.CharField(default='Heart', help_text="Nom de l'icà´ne (ex: Heart, Scale, Handshake, Shield)", max_length=50),
        ),
    ]
