# Generated by Django 6.0.4 on 2026-05-02 13:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_activity_options_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
