# Generated by Django 5.0.14 on 2026-05-16 18:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_activity_options_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activite', 'verbose_name_plural': 'Activites'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Article / Actualite', 'verbose_name_plural': 'Articles / Actualites'},
        ),
        migrations.AlterModelOptions(
            name='commemorationsection',
            options={'verbose_name': 'Section Commemoration (Accueil)', 'verbose_name_plural': 'Section Commemoration (Accueil)'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Evenement', 'verbose_name_plural': 'Evenements'},
        ),
        migrations.AlterModelOptions(
            name='memorialsite',
            options={'verbose_name': 'Lieu de Memoire', 'verbose_name_plural': 'Lieux de Memoire'},
        ),
        migrations.AlterModelOptions(
            name='pastedition',
            options={'ordering': ['-year'], 'verbose_name': 'Edition passee', 'verbose_name_plural': 'Editions passees'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['order'], 'verbose_name': 'Methode de paiement', 'verbose_name_plural': 'Methodes de paiement'},
        ),
        migrations.AlterModelOptions(
            name='programmeitem',
            options={'ordering': ['order'], 'verbose_name': 'Point du Programme', 'verbose_name_plural': 'Programme des commemorations'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Temoignage', 'verbose_name_plural': 'Temoignages'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': "Membre de l'equipe", 'verbose_name_plural': "Membres de l'equipe"},
        ),
        migrations.AlterModelOptions(
            name='testimonysubmission',
            options={'verbose_name': 'Soumission de Temoignage', 'verbose_name_plural': 'Soumissions de Temoignages'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order'], 'verbose_name': 'Event Chronologique', 'verbose_name_plural': 'Frise Chronologique (Massacre)'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order'], 'verbose_name': 'Video Galerie', 'verbose_name_plural': 'Videos Galerie'},
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('partner', 'Partenaire'), ('collaborator', 'Collaborateur')], default='partner', help_text='Partenaire institutionnel ou Collaborateur de terrain', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='achievements',
            field=models.JSONField(default=list, help_text='Liste des realisations (format JSON)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.CharField(help_text="Nom de l'icone Lucide (ex: MessageCircle)", max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='next_event',
            field=models.CharField(blank=True, help_text='Texte libre indiquant la date du prochain evenement', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(help_text="Annee de l'album"),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(help_text='Categorie affichee (ex: Memoire)', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commemorationsection',
            name='date_text',
            field=models.CharField(help_text='Ex: 30 Décembre 2025 – 2 Janvier 2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='commemorationsection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('rapports', 'Rapports annuels'), ('communiques', 'Communiques'), ('archives', 'Archives historiques'), ('ressources', 'Ressources pedagogiques')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('FR', 'Francais'), ('EN', 'English'), ('SW', 'Swahili')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donationimpact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donationintent',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prenom et nom'),
        ),
        migrations.AlterField(
            model_name='donationintent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donationintent',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Contacte / En cours'), ('completed', 'Finalise')], default='pending', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('dialogue', 'Dialogue'), ('formation', 'Formation'), ('soutien', 'Soutien'), ('commemoration', 'Commemoration'), ('gouvernance', 'Gouvernance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homectaaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='memorialsite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pastedition',
            name='highlight',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text="Fait marquant de l'edition"),
        ),
        migrations.AlterField(
            model_name='pastedition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programmeitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text="Texte d'a propos global (footer/home)"),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Temoignage complet'),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(help_text='Nom du temoin', max_length=150),
        ),
        migrations.AlterField(
            model_name='supportform',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testimonysubmission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testimonysubmission',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Valide ?'),
        ),
        migrations.AlterField(
            model_name='testimonysubmission',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Temoignage'),
        ),
        migrations.AlterField(
            model_name='testimonysubmission',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom et Prenom'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='value',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
