# Generated by Django 5.0.14 on 2026-05-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_activity_options_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo/Image'),
        ),
    ]
